FileTypes:
  Accepted:
    - "jpg"
    - "jpeg"
    - "png"
    - "bmp"
    - "exr"
    - "tif"
    - "tiff"
  NormalizeTypes:
    - "uint32" # not tested
    - "float32"
    - "float16" # not tested
    - "float14" # not tested
    - "uint16" # not tested
    - "uint14" # not tested 
    - "float" # not tested

DisplayFormats:
  float32:
    - Format_RGBX32FPx4
    - Format_RGBA32FPx4
  uint8:
    - Format_RGB888
    - Format_RGBA8888

  float16:
    - Format_RGBX16FPx4 # not tested
    - Format_RGBA16FPx4 # not tested